### ISSUE TITLE
Server not starting up

### ISSUE THREAD

**Issue by xe1os** [dasisdormax/cs2-multiserver#1]
Hi,

getting below error when checked in console.

Thank you.

![image](https://github.com/dasisdormax/cs2-multiserver/assets/39219862/ad5ead5b-82d6-453e-9354-3ca174c128fd)

**Comment by dasisdormax** [comment]
Thanks for the report.

Interestingly, you observed two different bugs at the same time. I think I got both of them fixed. If you get any more issues, feel free to tell me again.
