### ISSUE TITLE
__MAXPLAYERS__=x doesn't work

### ISSUE THREAD

**Issue by lostsoul6** [dasisdormax/cs2-multiserver#15]
Hello @dasisdormax 

I just ran a server with __MAXPLAYERS__=18 set in casual.conf preset but server is allowing 64 players . it seems this option is not working . How do I set max players ? Also how do we set reserved slots in msm ?

Here is my full casual.conf :

```
#! /bin/bash
## vim: noet:sw=0:sts=0:ts=4

# (C) 2016-2017 Maximilian Wende <dasisdormax@mailbox.org>
#
# This file is licensed under the Apache License 2.0. For more information,
# see the LICENSE file or visit: http://www.apache.org/licenses/LICENSE-2.0




#~~~~ GAMETYPE and GAMEMODE: These set the general gamemode to be used
#~~~~     See gamemodes.txt for a list of valid number combinations
#~~~~
#~~~~     Note that many gameplay-related settings will be loaded from
#~~~~     your instance's cs2/cfg/gamemode_<xyz>_server.cfg
__GAMETYPE__=0
__GAMEMODE__=0


#~~~~ MAXPLAYERS: The number of active players allowed, excluding spectators
#~~~~             The default value is gamemode-dependent
__MAXPLAYERS__=18


#~~~~ MAPGROUP: The mapgroup to be played, primarily used on vanilla servers
__MAPGROUP__="mg_asli"


#~~~~ MAPS: A list of single maps to be played. This is used to generate the mapcycle file
#~~~~       If no MAP is given, the first entry will be loaded on server start
__MAPS__="de_mirage de_dust2 de_inferno"

# Customize your GOTV Delay here. The default for competitive is 105 seconds.
# __TV_DELAY__=60



```

**Comment by dasisdormax** [comment]
Hi @lostsoul6 

> I just ran a server with MAXPLAYERS=18 set in casual.conf preset but server is allowing 64 players . it seems this option is not working.

Thanks for reporting, that's indeed a bug. The way the script sets the maxplayers does not work with CS2 anymore.

> Also how do we set reserved slots in msm ?

Reserved slots are a feature from Metamod and Sourcemod and (as far as I know) not a built-in feature of the Counter-Strike Server. So, you'll have to check the Metamod/Sourcemod instructions for that.

**Comment by lostsoul6** [comment]
@dasisdormax any fixes for maxplayers?

**Comment by dasisdormax** [comment]
Should be fixed with the latest commit. https://github.com/dasisdormax/cs2-multiserver/commit/47f6007497763a7c6f2f12e1901a0e15496020a3
