### ISSUE TITLE
Having problem joining server

### ISSUE THREAD

**Issue by kgplayz** [dasisdormax/cs2-multiserver#17]
So im planning to host a LAN tournament, got the server running but can not join in saying some type of error, would really appreciate your help😄

**Comment by dasisdormax** [comment]
Which error do you get?

**Comment by kgplayz** [comment]
So server started, tried to join with another computer and started loading in, other pc disconnected from server and said unstable connection and in my server pc i checked console for any information and after saying that my other account is entering the game, and after that connected and then steam userid validated and then sending full update  to client and then netchan setting timeout and then incoming timing out and then cant find client frame for world snapchat and then strapper kicked by console (network disconnect kicked)
and disassociating netchan so after that the server disappears from browse server

**Comment by kgplayz** [comment]
Or maybe you need some additional information?
