### ISSUE TITLE
Adding launch options

### ISSUE THREAD

**Issue by jenson2k** [dasisdormax/cs2-multiserver#2]
Maybe im just a little bit lost, but i cant find anything related to this.
I want to add some launch options during startup for an instance. Cant get it to work, also looked up the documentation for csgo-multiserver.
I tried adding the variables `__VAR__="bla"`, `VAR="bla"`, `__EXTRAPARAMS__="bla"`, `EXTRAPARAMS="bla"` to the instance config (/msm.d/cs2/cfg/(inst-instance1/cfg/server.cfg) but nothing seems to work. Also tried launching the instance with `VAR="bla" cs2-server @instance1 start` which wont change the launch settings.

**Comment by dasisdormax** [comment]
I don't get what you are trying to do. Do you want to extra command line arguments, or set specific cvars? What does `VAR` stand for in this case?

**Comment by jenson2k** [comment]
Found that in the csgo-serverlauncher docs. I want to start the server with arguments "-maxplayers +host_workshop_collections +host_workshop_map exec bla.cfg"

**Comment by dasisdormax** [comment]
- **About workshop hosting**: I haven't yet tried workshop hosting with CS2, but I heard it does not properly work yet.
- **About maxplayers:** There is a MAXPLAYERS variable that you can set. Does it not work?
- **About exec bla.cfg:** There are the bash arrays AUTOEXEC_CUSTOM, MAPCHANGE_CUSTOM and GAMEMODE_CUSTOM where you can add any command (including exec).

If you want to look into the syntax and details, you can start from the provided 'surf' preset and 'cs2/app/functions/genconfig.sh'. If some specific function does not work, feel free to tell me or just work on it yourself.

However, there is no option to add arbitrary command line arguments, and I don't plan to add this option.

**Comment by Wiethoofd** [comment]
isn't SDR also a launch option that needs to be set on server creation? or is that a TF2 only thing? how would you go about adding that, without modifying the server-start.sh of an instance?

**Comment by dasisdormax** [comment]
I haven't heard about SDR in the context of CS:GO or CS2. Do you have any resources on that?

**Comment by dasisdormax** [comment]
Workshop hosting is now implemented using the `WORKSHOP_COLLECTION_ID` and `WORKSHOP_MAP_ID` variables.
