### ISSUE TITLE
Stopping one instance closes all instances

### ISSUE THREAD

**Issue by Tastefull** [dasisdormax/cs2-multiserver#23]
Hi, 

I have 2 instances set up:
- GR1-15
- GR1-16

If i start both them using `cs2-server @gr1-15 start` and `cs2-server @gr1-16 start` they both run fine. But if do either `cs2-server @gr1-15 stop` or `cs2-server @gr1-16 stop`, both instances closes.

**Comment by dasisdormax** [comment]
I can't reproduce the issue. Do the logs show what happened to the other instance, that was supposed to keep running?

**Comment by Tastefull** [comment]
`cs2-server @gr1-15 start`
>cs@csserver:~/msm.d/cs2$ tail log/inst-gr1-15/240226_13\:01\:39-controller.log
>
> **INFO:**    in main                                         (  40)
>     This program will control the **cs2** server and react to events
>     such as server crashes, pending updates and user commands.
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> LAUNCHING
> **INFO:**    in main                                         ( 100)
>     Launching cs2 server ...
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> RUNNING
> 

`cs2-server @gr1-16 start`

> cs@csserver:~/msm.d/cs2$ tail log/inst-gr1-16/240226_13\:02\:24-controller.log
> 
> **INFO:**    in main                                         (  40)
>     This program will control the **cs2** server and react to events
>     such as server crashes, pending updates and user commands.
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> LAUNCHING
> **INFO:**    in main                                         ( 100)
>     Launching cs2 server ...
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> RUNNING
> 

`cs2-server @gr1-15 stop`

> Stopping Instance @gr1-15 ...
> **SUCCESS:**
>     Stopped **Instance @gr1-15**.
> 
> cs@csserver:~/msm.d/cs2$ tail log/inst-gr1-15/240226_13\:01\:39-controller.log
> **INFO:**    in main                                         ( 109)
>     Stopping ...
> **DEBUG:**   in App::killServer                              ( 136)
>              in try                                          (  65)
>              in Core.Wrapper::killServer                     (  80)
>              in Core.Wrapper::shutdownServer                 (  75)
>              in main                                         ( 110)
>     Killing server with pid = 121475 ...
> **INFO:**    in main                                         ( 150)
>     Server Stopped. Exiting ...
> 
> cs@csserver:~/msm.d/cs2$ tail log/inst-gr1-16/240226_13\:02\:24-controller.log
> **INFO:**    in main                                         ( 100)
>     Launching cs2 server ...
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> RUNNING
> **INFO:**    in main                                         ( 124)
>     Server exited with exit code 0.
> **DEBUG:**   in main                                         ( 146)
>     Current State: >>> STOPPED
> **INFO:**    in main                                         ( 150)
>     Server Stopped. Exiting ...
>

**Comment by Tastefull** [comment]
Hi,

So i use LAUNCH_CMD to override the startup parameters so i didn't set the __PORT__ so both were set to 27015 but my LAUNCH_CMD does include different port (27015 and 27016). I have just tried to set the __PORT___ to 27016 for the gr1-16 server config file, but both services still stops if i stop one of them. Right now my workaround is to send a QUIT command with the exec feature of cs2-server.

Is there a chance that because i set LAUNCH_CMD variable in server.conf there is stuff that are not set correctly? I noticed that i had to include the full path for cs2 like this  ./game/bin/linuxsteamrt64/cs2 because the home directory is set to /home/cs/msm.d/cs2/inst-gr1-15 and /home/cs/msm.d/cs2/inst-gr1-16. Which is not needed if i don't use LAUNCH_CMD.

here are the start response i get from the two instances

> Starting Instance @gr1-15 ...
> **INFO:**
>     Server working directory: **/home/cs/msm.d/cs2/inst-gr1-15**
> **INFO:**
>     Server launch command:
>         ./game/bin/linuxsteamrt64/cs2 -dedicated +map de_dust2 +game_mode
>         1 +game_type 0 -port 27015 +rcon_password XXXXXX -ip 192.168.1.10
>         +log on +sv_logecho 1 -maxplayers 10 +exec load-match.cfg
> **SUCCESS:**
>     **Instance @gr1-15** started successfully!
> 
>     Use **cs2-server @gr1-15 console** to enter the game's console.

> Starting Instance @gr1-16 ...
> **INFO:**
>     Server working directory: **/home/cs/msm.d/cs2/inst-gr1-16**
> **INFO:**
>     Server launch command:
>         ./game/bin/linuxsteamrt64/cs2 -dedicated +map de_dust2 +game_mode
>         1 +game_type 0 -port 27016 +rcon_password XXXXX -ip 192.168.1.10
>         +log on +sv_logecho 1 -maxplayers 10 +exec load-match.cfg
> **SUCCESS:**
>     **Instance @gr1-16** started successfully!
> 
>     Use **cs2-server @gr1-16 console** to enter the game's console.
>

**Comment by dasisdormax** [comment]
`LAUNCH_CMD` is generated by the script and was never intended to be set manually. While you could launch the servers, the remaining setup does not finish normally.

**Comment by Tastefull** [comment]
But it is documented in the code that it can be overridden. Could you supply a way to then add variables to the LAUNCH_CMD?  E.g. an EXTRA_CMD or something similar

**Comment by dasisdormax** [comment]
> But it is documented in the code that it can be overridden.

I'd like to see that documentation ...

> Could you supply a way to then add variables to the LAUNCH_CMD? E.g. an EXTRA_CMD or something similar

Extra cvars can be set in server.conf with AUTOEXEC_CUSTOM, for example
~~~
AUTOEXEC_CUSTOM=(
"mp_autokick 0"
"mp_autoteambalance 0"
"mp_freezetime 0"
"sv_airaccelerate 400"
"exec load-match.cfg"
)
~~~

If extra command line arguments are necessary (for example if setting some cvar in an autoexec file doesn't work), I am open to adding those specific ones, but I won't support arbitrary command line arguments.

**Comment by Tastefull** [comment]
Thanks for clarifying. I tried using the autoexec custom but didn't seem to work.

I think i can work my way around not having full control over the launch parameters. So thanks for helping out.

**Comment by Tastefull** [comment]
Thanks for clarifying. I tried using the autoexec custom but didn't seem to work.

I think i can work my way around not having full control over the launch parameters. So thanks for helping out.
