### ISSUE TITLE
strange situation. Server is not starting after stopping him

### ISSUE THREAD

**Issue by killtronic** [dasisdormax/cs2-multiserver#4]
hey,

I have a strange situation with my server instances.
All what I want to show is includen on the movie.
https://streamable.com/dy8zu4

Namely, if I want to start my server again after stopping him - nothing happening. Only way to fix it is reboot my machine.
Any ideas?

**Comment by dasisdormax** [comment]
Do the logs show something?

You can find them at `~/msm.d/cs2/log/inst-lan/`.

**Comment by killtronic** [comment]
[231110_00%3A09%3A31-controller.log](https://github.com/dasisdormax/cs2-multiserver/files/13318084/231110_00.3A09.3A31-controller.log)
[231110_00%3A09%3A31-server.log](https://github.com/dasisdormax/cs2-multiserver/files/13318085/231110_00.3A09.3A31-server.log)

**Comment by dasisdormax** [comment]
Thanks.

According to the logs, the server port is already in use. I guess that the previously launched server didn't stop and clean up properly.

You can try setting a different port with `PORT=27115 cs2-server @lan start`.
Also, you can diagnose, which program keeps the port occupied using `ss -ulpn` and try to kill it manually. Good luck!

Also, please do not run the script and the game server with the root account. That's an unnecessary security risk and I don't know if that also causes other issues.

**Comment by dasisdormax** [comment]
There actually was an issue where the server didn't stop properly. That was fixed with 82dd5659f6eb4601936210ac64a6fc4d34cb3f38 and should fix your issue.
