### ISSUE TITLE
stopping instance doesn't kill server & rcon password not setting

### ISSUE THREAD

**Issue by pretsell** [dasisdormax/cs2-multiserver#5]
Had a little play trying this out tonight, two issues so far.

Rcon password is not getting set after uncommenting USE_RCON & __RCON_PASS__ in the server.cfg. I'm fairly sure modifying right file as other changes are getting applied to the launch command.

And once you have stopped the instance the status shows as stopped but server process is still running.

I checked the logs and nothing useful unfortunately.

Any ideas?

**Comment by dasisdormax** [comment]
Thanks for the report. I'm investigating and working on a fix.

**Comment by dasisdormax** [comment]
Stopping the instance is fixed in 82dd5659f6eb4601936210ac64a6fc4d34cb3f38. I will look into the RCON issue later.

**Comment by dasisdormax** [comment]
I fixed an issue where 'autoexec.cfg' was not automatically executed. However, even with that fixed I did not get RCON to work.

So unfortunately, you'll have to try to fix it yourself or work with `cs2-server @yourinstance console` instead.

**Comment by pretsell** [comment]
Can confirm server stopping now works 👍

Added rcon_password "xyz" into server.cfg in ~/msm.d/cs2/base/game/csgo/cfg
That has done the trick for now.
