### ISSUE TITLE
confused at what this means

### ISSUE THREAD

**Issue by 0boris** [dasisdormax/cs2-multiserver#7]
Hey there, I need to run my server as root due to some issues that I'm running into on the project I'm working on, and the error says:

`If you know what you are doing and want to continue anyway, export MSM_I_KNOW_WHAT_I_AM_DOING_ALLOW_ROOT=1 and try again.`

How would this be done?

**Comment by dasisdormax** [comment]
I cite the rest of the error message:

> This is unsupported and can cause server malfunctions and security issues. Please consider using a regular user instead of root.

I don't provide support for running as root. Besides, the instruction to continue anyway is as literal as it gets.
