### ISSUE TITLE
Question about the script

### ISSUE THREAD

**Issue by lostsoul6** [dasisdormax/cs2-multiserver#9]
Hello There ,

my intention is to run multiple instances of cs2 servers on one single ubuntu 22 VPS ( port 27015 , 27016 and etc ) . Now what I don't understand is that you said your script uses the same base files to run multiple instances but what happens if  I want each of my instances to have their different plugins ? For example one server has vip plugin and it's own database and the other one has different plugins and different database . Can we still use your script to run those servers ? If not , what is the best way you suggest to me to run different cs2 server instances on the same VPS ?

Regards ,

**Comment by dasisdormax** [comment]
Running different plugins on different instances was supported with CS:GO, and should also work with CS2.

For this, just install the plugins as normal for each instance individually (to the directories `~/msm.d/cs2/inst-vip` and `~/msm.d/cs2/inst-other`). However, I have not tested it with CS2 yet, so please keep me up to date if it works or if you run into any issues.

**Comment by dasisdormax** [comment]
Discussion continues at #10
